package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseChannel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_channel", primaryKey = "id")
public class Channel extends BaseChannel<Channel> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_channel";

	
}
