package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BasePostContent;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_post_content", primaryKey = "id")
public class PostContent extends BasePostContent<PostContent> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_post_content";

	
}
