package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BasePost;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_post", primaryKey = "id")
public class Post extends BasePost<Post> {

	private static final long serialVersionUID = 1L;

	
}
