package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BasePostFavor;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_post_favor", primaryKey = "id")
public class PostFavor extends BasePostFavor<PostFavor> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_post_favor";

	
}
