package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseRoleUrl;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_role_url", primaryKey = "id")
public class RoleUrl extends BaseRoleUrl<RoleUrl> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_role_url";

	
}
