package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_role", primaryKey = "id")
public class Role extends BaseRole<Role> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_role";

	
}
