package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_user_role", primaryKey = "id")
public class UserRole extends BaseUserRole<UserRole> {

	private static final long serialVersionUID = 1L;

	public static final String table = "t_user_role";

	
}
