package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseWallet;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_wallet", primaryKey = "id")
public class Wallet extends BaseWallet<Wallet> {

	private static final long serialVersionUID = 1L;

	
}
