package okkpp.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "User:add";
    public static final String ACTION_DELETE = "User:delete";
    public static final String ACTION_UPDATE = "User:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setMood(java.lang.String mood) {
		set("mood", mood);
	}
	
	public java.lang.String getMood() {
		return getStr("mood");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

}
