package okkpp.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePost<M extends BasePost<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setAuthorId(java.lang.Long authorId) {
		set("author_id", authorId);
	}
	
	public java.lang.Long getAuthorId() {
		return getLong("author_id");
	}

	public void setChannelId(java.lang.Long channelId) {
		set("channel_id", channelId);
	}
	
	public java.lang.Long getChannelId() {
		return getLong("channel_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setViews(java.lang.Integer views) {
		set("views", views);
	}
	
	public java.lang.Integer getViews() {
		return getInt("views");
	}

	public void setFeatured(java.lang.Integer featured) {
		set("featured", featured);
	}
	
	public java.lang.Integer getFeatured() {
		return getInt("featured");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}
	
	public java.lang.Integer getWeight() {
		return getInt("weight");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}
	
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}

}