package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseBase;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_base", primaryKey = "id")
public class Base extends BaseBase<Base> {

	private static final long serialVersionUID = 1L;

	
}
