package okkpp.model;

import io.jboot.db.annotation.Table;
import okkpp.model.base.BaseUrl;

/**
 * Generated by Jboot.
 */
@Table(tableName = "t_url", primaryKey = "id")
public class Url extends BaseUrl<Url> {

	private static final long serialVersionUID = 1L;

	
}
